server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka


#eureka:
#  instance:
##    要求Client通过IP的方式进行注册
#    prefer-ip-address: true
#    instance-id: spring-cloud-eureka-200
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    service-url:
#      defaultZone: http://192.168.88.200:8761/eureka,http://192.168.88.201:8761/eureka
#
#  #actuator
#  management:
#    #配置了Actuator对外暴露REST API接口的端口号,如果不指定，端口为应用程序的启动端口，这样做的目的是将程序端口和程序的监控端口分开。
#    port: 8777
#    #Actuator 采取非安全验证方式,l.5x 版本默认开启了 Actuator 的安全验证。•
#    security:
#      enabled: false
